### ISSUE TITLE
Javascript Array Methods

### ISSUE THREAD

**Issue by cyouh95** [tobiasvc/billes-jammming#3]
Take a look at some of the array methods listed [here](https://www.w3schools.com/jsref/jsref_obj_array.asp) that you could use to help simplify your code. (For example, `.some()` in `addTrack()`, `.filter()` in `removeTrack()`, and `.map()` in `savePlaylist()`)

https://github.com/tobiasvc/billes-jammming/blob/master/src/Components/App/App.js#L24-L39
https://github.com/tobiasvc/billes-jammming/blob/master/src/Components/App/App.js#L40-L57
https://github.com/tobiasvc/billes-jammming/blob/master/src/Components/App/App.js#L66-L69

**Comment by tobiasvc** [comment]
Hi, 
thanks, i will get to know those functions better.
