### ISSUE TITLE
Booleans

### ISSUE THREAD

**Issue by cyouh95** [tobiasvc/billes-jammming#4]
Alternatively, you could use booleans instead of strings here (ie. `isRemoval={true}` or `isRemoval={false}`)

https://github.com/tobiasvc/billes-jammming/blob/master/src/Components/Playlist/Playlist.js#L23
https://github.com/tobiasvc/billes-jammming/blob/master/src/Components/SearchResults/SearchResults.js#L10

**Comment by tobiasvc** [comment]
noted
